git:
  depth: 1
os:
  - linux
language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: release
  target-branch: master
  on:
    branch: development